### ISSUE TITLE
5월 2주차 스프린트 TODO List

### ISSUE THREAD

**Issue by GoBeromsu** [GoBeromsu/Blind-Tok#33]
# Backend
- [ ] 프론트랑 페이지 API 붙일 것
- [x] Socket.io 채팅을 하는데 서버 측에서 어떻게 처리를 할 것인지 구체화
- [x] cors 문제 해결
- [x] query 폴더(data) 정리

# Frontend
## 공통 사항
- [x] query 폴더(data) 정리
- 필요한 쿼리 등은 백엔드에게 꼭 카톡으로 요청

## 승주
- [ ] WebRTC - Kurento로 보이스 채팅 기능
- [x] socket.io 채팅을 하는데 채팅 내용을 로컬에 저장하는 기능
 
## 우엽
- [x] cors 문제 프로튼에서 해결 방안 찾기
- [x] 로그인 페이지
- [ ] 영상 업로드 기능 페이지(프로필 등)에 추가
