### ISSUE TITLE
Fix : TS 마이그레이션 함에 따라 CI 수정 필요

### ISSUE THREAD

**Issue by GoBeromsu** [GoBeromsu/Blind-Tok#38]
## Todo List
- [x] Github Action 프론트 환경 변수 (구글 로그인) 설정
- [x] 의존성 변경에 따른 명령어 수정
- [x] 사용하는 라이브러리가 달라서 이에 대한 유효성 검증 필요
