### ISSUE TITLE
5월 4째 주 스프린트

### ISSUE THREAD

**Issue by GoBeromsu** [GoBeromsu/Blind-Tok#84]
## Todo List

- [ ] 메인 페이지 - 우엽
    - [ ] 모든 오디오 파일 리스트 가져오기
    - [ ] 단일 컴포넌트 클릭하면 해당 유저 페이지로 이동
    - [ ] 친구 요청 보내기
- [ ] 마이(유저) 페이지 - 승주
    - [ ] 파일 업로드
    - [ ] 상태 메시지
- [ ] 로그아웃 페이지 - 우엽
- [ ] 알림 페이지 - 승주
    - [ ] 친구 요청 리스트
- [ ] 검색 기능

이슈를 생성하거나 기존의 이슈에 추가하여 작업을 추적할 수 있습니다.
